---
version: '3'

services:

  server:
    build: .
    image: index.docker.io/oaklabs/component-payment:${VERSION-latest}
    environment:
      - PORT=9102
      - DEBUG=true
      - NODE_ENV=development
    volumes:
      - ./src:/app/src/
      - ./test:/app/test/
      - ./protos:/protos/
