---
version: '3'

services:

  server:
    build: .
    image: index.docker.io/oaklabs/component-oak-lights:${VERSION-latest}
    network_mode: host
    environment:
      - PORT=9100
    devices:
      - /dev/ttyACM0