---
version: '3'
volumes:
  app-persistent-storage:
services:
  filesync-test:
    build: .
    image: filesync-example
    volumes:
      - /dev/shm:/dev/shm
      - app-persistent-storage:/persistent
    environment:
      - CONTROL_PORT=9102
      - DATA_PORT=9103
      - GS_URL=gs://oak-test/onefile
      - SYNC_DIR=/persistent/files
      - SYNC_PERIOD=600
    ports:
      - "9102:9102"
      - "9103:9103"
