---
version: '3'

services:

  server:
    build: .
    image: index.docker.io/oaklabs/component-google-fluentd:${VERSION-latest}
    volumes:
      - ./sample-google-fluentd.conf:/fluentd.conf
      - ./gcp-credentials.json:/application_default_credentials.json
